# Generated by Django 2.2.12 on 2024-12-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentreponse',
            name='is_True',
        ),
        migrations.AlterField(
            model_name='studentreponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reponse_question', to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='studentreponse',
            name='reponse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studentreponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reponse_student', to='student.Student'),
        ),
    ]
